package aor.paj.service.status;

public enum Function {
    PERMANENTLY_USER_DELET,
    GET_OTHER_USER_INFO,
    EDIT_OWN_USER_INFO,
    EDIT_OTHER_USER_INFO,
    EDIT_OR_DELETE_OTHER_USER_TASK,
    GET_ALL_TASKS,
    GET_ALL_TASKS_BY_USER,
    GET_ALL_TASKS_BY_CATEGORY,
    GET_ALL_TASKS_BY_CATEGORY_AND_USER,
    RECYCLY_TASK_BY_ID,
    DELETE_ALL_TASKS_BY_USER_TEMPORARILY,
    DELETE_TASK_PERMANENTLY,
    GET_ALL_TASKS_DELETED
}
